openapi: 3.0.0
info:
  title: Todo API
  version: 1.0.0
  description: API documentation for the Todo backend service.
servers:
  - url: http://localhost:5000
paths:
  /todos:
    get:
      summary: Get all todos
      responses:
        '200':
          description: List of todos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref:'#/components/schemas/Todo'
    post:
      summary: Create a new todo item  
      requestBody: 
        required: true
        content:
          application/json:
            schema:
              $ref:'#/components/schemas/TodoInput'
      responses:
        '201':
          description: Todo created
          content:
            application/json:
              schema:
                $ref:'#/components/schemas/Todo'
/todos/{id}:
  put:
    summary: Update a todo
    parameters:
      -in: path
      name: id
      required: true 
      schema:
        type: string
    requestBody:
      required: true 
      content:  
        application/json:
          schema:
            $ref:'#/components/schemas/TodoInput'
    responses:
      '202':
        description: Updated a todo
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Todo'
  delete:
  summary: Delete a todo
  parameters: 
    -in: path
    name: id
    required: true
    schema:
      type: string
  responses:
    '202':
      description: Deleted a todo
      content:
        application/json:
          schema:
            $ref:'#/components/schemas/Todo'
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
        text:
          type: string
        completed:
          type: boolean
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - text
        - completed
        - createdAt
    TodoInput:
      type: object
      properties:
        text:
          type: string
      required:
        - text